language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: 5.3

before_script:
 - composer self-update
 - composer install --prefer-source --dev

script:
  - mkdir -p build/logs
  - cd tests
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
