language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - '7'

matrix:
    allow_failures:
        - php: 5.3
        - php: hhvm

before_script:
 - composer self-update
 - composer install --prefer-source

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - cd tests
  - php ../vendor/phpunit/phpunit/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover ../build/logs/clover.xml; fi
